# We start from a uv image to make life easier.
FROM materialsvirtuallab/lammps_gnnp:latest

ENV DGLBACKEND=pytorch
ENV MATGL_BACKEND=DGL

RUN uv pip install --system matgl matcalc matpes "numpy<2" dgl==2.1.0 torch==2.2.0 torchdata==0.7.1
